### ISSUE TITLE
Crash when clicking Video Settings

### ISSUE THREAD

**Issue by asteroidb12** [Featurehouse/bright-ore#2]
Hello, I am having crashes every time I click Video Settings Button

Here's the crash log:
[crash-2021-05-11_16.57.11-client.txt](https://github.com/Featurehouse/bright-ore/files/6462639/crash-2021-05-11_16.57.11-client.txt)

Mods:
![image](https://user-images.githubusercontent.com/68461874/117900579-549b0100-b27e-11eb-9e43-e74c77774a28.png)

If you need anymore details, you can ask me.
Thank you!

**Comment by teddyxlandlee** [comment]
Received. Thanks for your feedback.  
Progressing...

**Comment by teddyxlandlee** [comment]
Since the mod mainly serves 1.17, we're sorry that your request might won't be solved on time.  
It is a coincidence that this mod can run in 1.16.5 in early versions. We're looking for the cause that makes game crashes.

**Comment by teddyxlandlee** [comment]
I feel damn that I don't know how to struggle between Java-8-based Minecraft 1.16.5 and Java-16-based Minecraft 21w19a. Forgive me that I should deal with this first.

**Comment by teddyxlandlee** [comment]
This has already fixed.
